statesCrop = [
["Andhra Pradesh", "500-1200 mm", "Rice", "Groundnut", "Sugarcane", "Cotton", "Tobacco"],
["Arunachal Pradesh", "1500-4000 mm", "Rice", "Maize", "Millet", "Wheat", "Soybean, Pigeon Pea"],
["Assam", "1500-3000 mm", "Rice", "Tea", "Jute", "Lentil, Black Gram", "Sugarcane"],
["Bihar", "800-1200 mm", "Rice", "Wheat", "Maize", "Lentil, Pigeon Pea", "Sugarcane"],
["Chhattisgarh", "800-1200 mm", "Rice", "Wheat", "Gram, Pigeon Pea", "Soybean, Mustard", "Maize"],
["Goa", "2500-3500 mm", "Rice", "Cashew Nuts", "Coconuts", "Mango, Pineapple", "Cucumber, Okra"],
["Gujarat", "300-800 mm", "Cotton", "Groundnut", "Wheat", "Rice", "Bajra"],
["Haryana", "300-700 mm", "Wheat", "Rice", "Cotton", "Sugarcane", "Mustard, Chickpea"],
["Himachal Pradesh", "500-3000 mm", "Wheat", "Maize", "Rice", "Lentil, Chickpea", "Apple, Plum, Apricot"],
["Jharkhand", "800-1200 mm", "Rice", "Wheat", "Maize", "Pigeon Pea, Lentil", "Tomato, Cauliflower"],
["Karnataka", "500-2000 mm", "Rice", "Ragi", "Jowar", "Maize", "Pigeon Pea, Green Gram"],
["Kerala", "1500-3000 mm", "Rice", "Coconut", "Rubber", "Tea", "Coffee"],
["Madhya Pradesh", "600-1000 mm", "Wheat", "Soybean", "Gram, Pigeon Pea", "Rice", "Cotton"],
["Maharashtra", "600-2000 mm", "Cotton", "Soybean", "Jowar", "Bajra", "Pigeon Pea, Green Gram"],
["Manipur", "1000-2000 mm", "Rice", "Pineapple, Banana", "Cabbage, Tomato", "Soybean", "Black Gram"],
["Meghalaya", "2000-12000 mm", "Rice", "Maize", "Black Gram, Green Gram", "Soybean", "Citrus, Pineapple"],
["Mizoram", "2000-3000 mm", "Rice", "Maize", "Black Gram, Green Gram", "Soybean", "Banana, Pineapple"],
["Nagaland", "1500-2500 mm", "Rice", "Maize", "Black Gram, Green Gram", "Soybean", "Banana, Pineapple"],
["Odisha", "1000-1600 mm", "Rice", "Pigeon Pea, Green Gram", "Groundnut, Mustard", "Brinjal, Tomato", "Mango, Banana"],
["Punjab", "300-800 mm", "Wheat", "Rice", "Cotton", "Sugarcane", "Chickpea, Lentil"],
["Rajasthan", "300-700 mm", "Bajra", "Wheat", "Mustard", "Gram, Green Gram", "Cotton"],
["Sikkim", "2000-4000 mm", "Rice", "Maize", "Millet", "Orange, Guava", "Cabbage, Radish"],
["Tamil Nadu", "600-1800 mm", "Rice", "Groundnut", "Pigeon Pea, Black Gram", "Cotton", "Sugarcane"],
["Telangana", "700-1200 mm", "Rice", "Cotton", "Maize", "Pigeon Pea, Green Gram", "Sunflower, Soybean"],
["Tripura", "2000-3000 mm", "Rice", "Pineapple, Banana", "Cabbage, Tomato", "Black Gram, Green Gram", "Soybean"],
["Uttar Pradesh", "300-1000 mm", "Wheat", "Rice", "Sugarcane", "Pigeon Pea, Lentil", "Mustard, Groundnut"],
["Uttarakhand", "800-1500 mm", "Rice", "Wheat", "Lentil, Horse Gram", "Litchi, Mango", "Potato, Pea"],
["West Bengal", "1500-3000 mm", "Rice", "Jute", "Tea", "Potato", "Banana, Mango"],
["Andaman and Nicobar Islands", "2500-3500 mm", "Rice", "Coconut", "Banana, Mango", "Cucumber, Pumpkin", "Black Pepper, Clove"],
["Chandigarh", "600-800 mm", "Wheat", "Rice", "Guava, Mango", "Potato, Cauliflower", "Lentil, Chickpea"],
["Dadra and Nagar Haveli and Daman and Diu", "1000-2000 mm", "Rice", "Mango, Chikoo", "Brinjal, Tomato", "Pigeon Pea, Green Gram", "Groundnut"],
["Delhi", "600-800 mm", "Wheat", "Rice", "Guava, Mango", "Potato, Cauliflower", "Lentil, Chickpea"],
["Lakshadweep", "1000-2000 mm", "Coconut", "Banana, Mango", "Cucumber, Pumpkin", "Pigeon Pea, Green Gram", "Groundnut"],
["Puducherry", "1000-1500 mm", "Rice", "Mango, Guava", "Brinjal, Tomato", "Black Gram, Green Gram", "Groundnut"]
]
